### PR TITLE
Support component(1)

### PR DESCRIPTION
**Pull request by sankargorthi**

### CODE REVIEW

**Comment by arendjr** [comment]
Cool, thanks!

**Comment by sankargorthi** [comment]
woo!

also, that was quick! I hadn't had time to test if this works.

**Comment by arendjr** [comment]
Hehe, I was just checking to see if there were any updates, then I noticed someone created a new fork. I checked out your commits before the PR even arrived :)

Anyway, I don't use component myself, so didn't check that either, but at least it seems unlikely you broke anything... well, unless the instructions in the README are faulty. Let me know if it works alright!

Cheers!

**Comment by sankargorthi** [comment]
Didn't work. It's 'cause of the `var $ = window.jQuery || window.Zepto;` at 9 locations in the codebase. `component(1)` usage sometimes means that jQuery is also pulled in as a component dependency as opposed to it being an implicit global. Are you open to adding a `var $ = require('jquery') || window.jquery...` modification to the library?

**Comment by sankargorthi** [comment]
works fine with an implicit global jquery dependency.

**Comment by arendjr** [comment]
I use var `$ = require('jquery')` everywhere in the sources. This also helps to make sure it works correctly in the unit tests which use NodeUnit. The build phase however performs a search and replace which turns it into `var $ = window.jQuery || window.Zepto;` so that it doesn't depend on the user having CommonJS environment.

So yes, I would be open to such modification, as it would just mean a small tweak to the build process. Do you think `var $ = (typeof require === 'function' ? require('jquery') : window.jQuery || window.Zepto)` would be sufficient?

Would you mind testing it out? You can find the replacement being done at line 39 of gulp/tasks/browserify-full.js and again at line 56 of gulp/tasks/browserify-custom.js (I have some work in progress to unify these two files). Thanks!

**Comment by sankargorthi** [comment]
spoke too soon. this would require that you declare jquery as an explicit dependency in the `component.json`. that'd be bad practice in general, as you'd have to maintain the version of jquery in there and it's better to leave that up to the consumer. trying to see how the local scope can be accessed.

**Comment by sankargorthi** [comment]
coming back to this later. also, trying to see how the select2 library works as described in the `Usage` I'd added to the Readme.md

**Pull request merged**
